# Generated by Django 5.2.9 on 2025-12-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Votación Activa')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'Configuración de Votación',
                'verbose_name_plural': 'Configuración de Votación',
            },
        ),
    ]
